#
## This package is mirrored to an internal NPM registry
#

image: node:16-alpine

stages:
  - release

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/'

release:
  stage: release
  script:
    - npm ci
    - npm run build
    - npm publish
